export const PERSON = {
  name: 'Darshan Joshi',
  title: 'AI Engineer · Computer Vision · NLP · Cybersecurity',
  email: 'joshidarshan193@gmail.com',
  phone: '+1 947 240 5099',
  location: 'Southfield, MI, USA',
  linkedin: 'https://linkedin.com/in/darshanjoshi05',
  github: 'https://github.com/darshanjoshi05',
  scholar: 'https://scholar.google.com/scholar?q=Darshan+Joshi+AI+Engineer',
  bio: [
    "I'm a CS engineer at the intersection of AI research and production engineering. Currently a Research Assistant at Lawrence Technological University, I build real-time behavior detection systems with YOLOv8 and PyTorch — from dataset curation and YAML pipeline design through Grad-CAM explainability and deployment.",
    "My technical range spans computer vision (YOLOv8, Grad-CAM, OpenCV), NLP and API engineering (FastAPI, regex pipelines, document generation), deep learning (CNN-LSTM hybrid models for seismic prediction), and cybersecurity (buffer overflow analysis, exploit research, EC-Council certified across 5 domains).",
    "I have 4 published and in-progress research papers spanning enterprise cybersecurity, AI-based behavior detection, earthquake prediction with CNN-LSTM, and NLP-driven document intelligence. I care deeply about model interpretability, responsible AI, and clean modular architecture.",
  ],
  stats: [
    { value: '3.75', label: "Master's GPA" },
    { value: '4',    label: 'Publications' },
    { value: '9',    label: 'Projects' },
    { value: '5',    label: 'EC-Council Certs' },
  ],
}

export const SKILLS = [
  // Core AI / ML — from YOLOv8x classroom, indoor YOLOv5, earthquake CNN-LSTM
  { name: 'Python',        hot: true },
  { name: 'PyTorch',       hot: true },
  { name: 'YOLOv8x',      hot: true },
  { name: 'YOLOv5',       hot: false },
  { name: 'Grad-CAM',     hot: true },
  { name: 'OpenCV',       hot: false },
  { name: 'Scikit-Learn', hot: false },
  { name: 'XGBoost',      hot: false },
  { name: 'Prophet',      hot: false },
  // NLP & Backend — from Resume Intelligence Engine
  { name: 'FastAPI',      hot: true },
  { name: 'NLP',          hot: true },
  { name: 'LLM',          hot: true },
  { name: 'REST APIs',    hot: false },
  { name: 'Pydantic',     hot: false },
  { name: 'SQLite',       hot: false },
  // Data & Visualization — from Twitter analytics, sorting benchmark
  { name: 'Pandas',       hot: false },
  { name: 'NumPy',        hot: false },
  { name: 'Matplotlib',   hot: false },
  { name: 'Seaborn',      hot: false },
  // Document generation — from Resume Intelligence Engine
  { name: 'ReportLab',    hot: false },
  { name: 'python-docx',  hot: false },
  // Security & Systems — from buffer overflow, EC-Council
  { name: 'GDB',          hot: false },
  { name: 'C / C++',      hot: false },
  { name: 'x86 ASM',      hot: false },
  // Database — from Global Harvest Imports
  { name: 'MySQL',        hot: false },
  { name: 'SQL',          hot: false },
  // DevOps & Frontend
  { name: 'Docker',       hot: false },
  { name: 'React',        hot: false },
  { name: 'Vite',         hot: false },
  { name: 'Git',          hot: false },
  // Research tools
  { name: 'Google Colab', hot: false },
  { name: 'Roboflow',     hot: false },
  { name: 'YAML',         hot: false },
  { name: 'Jupyter',      hot: false },
]

export const EXPERIENCE = [
  {
    role: 'Research Assistant',
    org: 'Lawrence Technological University',
    location: 'Southfield, MI',
    period: 'Dec 2024 — Present',
    current: true,
    points: [
      'Led end-to-end development of an AI-based classroom behavior detection system using YOLOv8 with measurable Precision, Recall, and mAP performance metrics.',
      'Designed and curated structured multi-class datasets (11+ behavioral classes), enforcing annotation quality under limited hardware resources.',
      'Integrated Grad-CAM explainability techniques to enhance model interpretability and support responsible AI practices.',
      'Conducted iterative hyperparameter optimization and documented reproducible YAML-based training workflows.',
      'Collaborated with faculty advisors to refine experimental scope and presented findings in structured research updates.',
      'Independently troubleshot training instability, environment configuration issues, and dataset inconsistencies.',
      'Maintained organized documentation of experiments, configuration files, and dataset revisions for long-term sustainability.',
    ],
  },
]

export interface Project {
  id: string
  num: string
  name: string
  tagline: string
  description: string
  stack: string[]
  category: string[]
  featured: boolean
  github: string
  period: string
  overview: {
    type: string
    status: string
    year: string
    role: string
  }
  stats: { value: string; label: string }[]
  bullets: string[]
  architecture: {
    nodes: { id: string; label: string; sublabel: string; color: string; row: number; col: number }[]
    edges: { from: string; to: string }[]
  }
  gallery: {
    title: string
    description: string
    type: 'terminal' | 'metrics' | 'json' | 'structure' | 'scores'
  }[]
  insights: string
}

export const PROJECTS: Project[] = [
  {
    id: 'resume-intelligence-engine',
    num: '01',
    name: 'Resume Intelligence Engine',
    tagline: 'Full-Stack AI Job Application System · FastAPI + LLM + ATS',
    description: 'A production-grade AI job application system with 25+ Python modules, a web dashboard, LLM-powered extraction, ATS scoring, recruiter outreach automation, and an adaptive learning engine. Generates tailored resumes and cover letters from job descriptions with 87%+ suitability accuracy.',
    stack: ['FastAPI', 'Python', 'LLM', 'SQLite', 'NLP', 'Jinja2', 'HTML/CSS/JS', 'ReportLab', 'python-docx', 'pytest'],
    category: ['ai', 'backend'],
    featured: true,
    github: 'https://github.com/darshanjoshi05/Resume-Intelligence-Engine',
    period: '2026 – Present',
    overview: { type: 'Full-Stack AI System', status: 'Active Development', year: '2026', role: 'Solo Engineer' },
    stats: [
      { value: '25+', label: 'Python Modules' },
      { value: '87%+', label: 'ATS Suitability' },
      { value: '5', label: 'Output Formats' },
    ],
    bullets: [
      'Built a full-stack AI job application system with FastAPI backend, web dashboard (HTML/CSS/JS), and SQLite job database (`jobs.db`, `db.py`).',
      'Implemented dual extraction pipeline: regex/NLP heuristics (`jd_extract.py`) + LLM-powered extraction (`llm_extract.py`) for maximum JD parsing accuracy.',
      'Designed ATS scoring and sanitization engine (`ats_check.py`, `ats_sanitize.py`) ensuring generated resumes pass Applicant Tracking Systems.',
      'Built adaptive learning system (`learner.py`, `learn_jd.py`, `learning_store.py`, `term_memory.py`) that improves skill matching over time.',
      'Engineered recruiter outreach automation (`recruiter_msg.py`) generating personalized cold emails from JD context.',
      'Developed modular generation pipeline: role detection → skill bridging → suitability scoring → template selection → PDF/DOCX export.',
      'Wrote full test suite with pytest (`tests/`, `pytest.ini`, `quality_gates.py`) ensuring production-grade reliability.',
    ],
    architecture: {
      nodes: [
        { id: 'jd',       label: 'JD Input',          sublabel: 'URL · Text · Paste',  color: 'blue',   row: 0, col: 0 },
        { id: 'app',      label: 'FastAPI App',        sublabel: 'app.py · REST API',   color: 'purple', row: 1, col: 0 },
        { id: 'extract',  label: 'JD Extractor',      sublabel: 'jd_extract.py',        color: 'blue',   row: 2, col: 0 },
        { id: 'llm',      label: 'LLM Extractor',     sublabel: 'llm_extract.py',       color: 'blue',   row: 2, col: 1 },
        { id: 'role',     label: 'Role Detector',     sublabel: 'role_detect.py',       color: 'blue',   row: 2, col: 2 },
        { id: 'ats',      label: 'ATS Engine',        sublabel: 'ats_check.py',         color: 'amber',  row: 3, col: 0 },
        { id: 'suit',     label: 'Suitability',       sublabel: 'suitability.py',       color: 'amber',  row: 3, col: 1 },
        { id: 'bridge',   label: 'Skill Bridge',      sublabel: 'skill_bridge.py',      color: 'amber',  row: 3, col: 2 },
        { id: 'learn',    label: 'Learner',           sublabel: 'learner.py',           color: 'purple', row: 4, col: 0 },
        { id: 'gen',      label: 'Generator',         sublabel: 'generator.py',         color: 'amber',  row: 4, col: 1 },
        { id: 'recruiter',label: 'Recruiter Msg',     sublabel: 'recruiter_msg.py',     color: 'purple', row: 4, col: 2 },
        { id: 'pdf',      label: 'PDF Export',        sublabel: 'ReportLab',            color: 'green',  row: 5, col: 0 },
        { id: 'docx',     label: 'DOCX Export',       sublabel: 'python-docx',          color: 'green',  row: 5, col: 1 },
        { id: 'dash',     label: 'Dashboard',         sublabel: 'dashboard.html',       color: 'green',  row: 5, col: 2 },
      ],
      edges: [
        { from: 'jd', to: 'app' },
        { from: 'app', to: 'extract' }, { from: 'app', to: 'llm' }, { from: 'app', to: 'role' },
        { from: 'extract', to: 'ats' }, { from: 'llm', to: 'suit' }, { from: 'role', to: 'bridge' },
        { from: 'ats', to: 'learn' }, { from: 'suit', to: 'gen' }, { from: 'bridge', to: 'gen' },
        { from: 'learn', to: 'gen' }, { from: 'gen', to: 'pdf' }, { from: 'gen', to: 'docx' },
        { from: 'gen', to: 'recruiter' }, { from: 'recruiter', to: 'dash' }, { from: 'pdf', to: 'dash' },
      ],
    },
    gallery: [
      { title: 'API Terminal Output', description: 'FastAPI server live generation log', type: 'terminal' },
      { title: 'Skill Match Scores', description: 'ATS + suitability scoring per skill', type: 'scores' },
      { title: 'JSON API Response', description: 'Structured generation payload', type: 'json' },
      { title: 'Project Structure', description: '25+ module file organization', type: 'structure' },
    ],
    insights: '### What I Built\n\nA **production-grade AI job application system** — far beyond a simple resume generator. It learns from JDs, scores ATS compatibility, auto-generates recruiter emails, and serves everything through a web dashboard.\n\n### Real Module Breakdown\n\n- **Extraction**: `jd_extract.py` (regex/NLP) + `llm_extract.py` (LLM-powered) — dual pipeline for maximum accuracy\n- **ATS**: `ats_check.py` + `ats_sanitize.py` — ensures output passes real ATS filters\n- **Learning**: `learner.py` + `learning_store.py` + `term_memory.py` — adaptive skill matching that improves over time\n- **Outreach**: `recruiter_msg.py` — personalized cold emails auto-generated from JD context\n- **Dashboard**: `dashboard.html` + `static/` + `templates/` — full web UI served by FastAPI\n- **Database**: `jobs.db` + `db.py` — SQLite job tracking and history\n- **Quality**: `tests/` + `quality_gates.py` + `pytest.ini` — production test suite\n\n### Key Engineering Decisions\n\n- Chose SQLite over PostgreSQL for zero-config portability\n- Dual extraction (regex + LLM) gives fallback resilience\n- `term_memory.py` stores domain-specific terminology across sessions for better matching\n\n### Next Steps\n\n- Deploy as SaaS with user authentication\n- Add real-time JD scraping from LinkedIn/Indeed',
  },
  {
    id: 'classroom-behavior-detection',
    num: '02',
    name: 'Classroom Behavior Detection System',
    tagline: 'YOLOv8x · 74.85% mAP@0.5 · Real-Time Inference',
    description: 'Production-grade classroom behavior detection system trained on the SCB-05 dataset using YOLOv8x on Google Colab Pro (A100 GPU). Achieves 74.85% mAP@0.5 overall and 93.5% detection accuracy on sleeping behavior across 11+ behavioral classes. Includes tiled inference pipeline for live CCTV/RTSP feeds.',
    stack: ['YOLOv8x', 'PyTorch', 'Google Colab', 'Roboflow', 'Grad-CAM', 'OpenCV', 'Python', 'YAML'],
    category: ['ai'],
    featured: false,
    github: 'https://github.com/darshanjoshi05',
    period: 'Dec 2024 – Present',
    overview: { type: 'Computer Vision', status: 'Active Research', year: '2025', role: 'Research Assistant' },
    stats: [
      { value: '74.85%', label: 'mAP@0.5' },
      { value: '93.5%',  label: 'Sleep Detection' },
      { value: '11+',    label: 'Behavior Classes' },
    ],
    bullets: [
      'Trained YOLOv8x on the SCB-05 dataset using Google Colab Pro with A100 GPU, achieving 74.85% mAP@0.5 across 11+ behavioral classes.',
      'Achieved 93.5% detection accuracy on sleeping behavior — the highest per-class precision in the model.',
      'Built tiled inference pipeline for live CCTV/RTSP feed processing, enabling real-time classroom monitoring.',
      'Curated and annotated multi-class dataset via Roboflow with rigorous quality control across hundreds of images.',
      'Configured reproducible YAML-based training pipelines with systematic hyperparameter optimization (batch size, image size, epochs).',
      'Integrated Grad-CAM explainability to validate that the model focuses on posture and body position rather than facial features.',
      'Designed architecture for deployment on resource-constrained campus hardware with streaming video input.',
    ],
    architecture: {
      nodes: [
        { id: 'scb',     label: 'SCB-05 Dataset',   sublabel: 'Roboflow Annotated',   color: 'blue',   row: 0, col: 0 },
        { id: 'aug',     label: 'Augmentation',     sublabel: 'Resize · Flip · Mosaic', color: 'blue', row: 1, col: 0 },
        { id: 'yolo',    label: 'YOLOv8x',          sublabel: 'A100 · Colab Pro',     color: 'purple', row: 2, col: 0 },
        { id: 'train',   label: 'Training Loop',    sublabel: 'YAML Config · GPU',    color: 'purple', row: 3, col: 0 },
        { id: 'eval',    label: 'Evaluation',       sublabel: 'mAP@0.5 = 74.85%',    color: 'amber',  row: 4, col: 0 },
        { id: 'gradcam', label: 'Grad-CAM',         sublabel: 'Explainability',       color: 'amber',  row: 4, col: 1 },
        { id: 'tiled',   label: 'Tiled Inference',  sublabel: 'CCTV · RTSP Feed',    color: 'green',  row: 5, col: 0 },
        { id: 'out',     label: 'Detection Output', sublabel: 'Bounding Boxes · Live', color: 'green', row: 5, col: 1 },
      ],
      edges: [
        { from: 'scb', to: 'aug' }, { from: 'aug', to: 'yolo' },
        { from: 'yolo', to: 'train' }, { from: 'train', to: 'eval' },
        { from: 'train', to: 'gradcam' }, { from: 'eval', to: 'tiled' },
        { from: 'gradcam', to: 'tiled' }, { from: 'tiled', to: 'out' },
      ],
    },
    gallery: [
      { title: 'Training Output', description: 'YOLOv8x Colab A100 training logs', type: 'terminal' },
      { title: 'Class mAP Scores', description: 'Per-class detection performance', type: 'scores' },
      { title: 'Training Config', description: 'YAML training configuration', type: 'json' },
      { title: 'Dataset Structure', description: 'SCB-05 Roboflow directory layout', type: 'structure' },
    ],
    insights: '### Research Context\n\nThis is my primary **research assistantship project** at Lawrence Technological University — a production-grade classroom behavior detection system trained on the SCB-05 dataset.\n\n### Key Results\n\n- **74.85% mAP@0.5** overall across 11+ behavioral classes\n- **93.5% accuracy** on sleeping detection — highest per-class precision\n- Trained on **Google Colab Pro (A100 GPU)** for fast iteration\n\n### Technical Highlights\n\n- **YOLOv8x** (extra-large model) chosen for maximum accuracy over speed\n- **Roboflow** used for dataset curation, annotation, and augmentation pipeline\n- **Tiled inference** enables deployment on wide-angle CCTV footage without losing small-object detection\n- **Grad-CAM** confirmed model attends to posture/body position, not faces — responsible AI validated\n\n### Next Steps\n\n- Streamlit analytics dashboard for live monitoring\n- Real-time RTSP stream integration for campus deployment\n- Paper submission to IJSRST (Under Review)',
  },
  {
    id: 'buffer-overflow-attack-lab',
    num: '03',
    name: 'Buffer Overflow Attack Lab',
    tagline: 'Cybersecurity Research · Low-Level Systems',
    description: 'Analyzed buffer overflow vulnerabilities in 32-bit environments — stack smashing, heap overflow, format string attacks. Evaluated ASLR and stack canary countermeasures using GDB.',
    stack: ['C', 'GDB', 'x86 ASM', 'ASLR', 'Linux', 'Shell'],
    category: ['security'],
    featured: false,
    github: 'https://github.com/darshanjoshi05',
    period: 'Jan – Jun 2024',
    overview: { type: 'Security Research', status: 'Completed', year: '2024', role: 'Solo Researcher' },
    stats: [{ value: '3', label: 'Attack Vectors' }, { value: 'x86', label: 'Architecture' }, { value: 'Root', label: 'Privilege Level' }],
    bullets: [
      'Analyzed buffer overflow vulnerabilities in 32-bit environments, identifying security weaknesses.',
      'Manipulated memory locations and return addresses to bypass execution restrictions.',
      'Developed and tested exploit code to achieve root access via code injection and privilege escalation.',
      'Explored stack smashing, heap overflow, and format string attacks to evaluate security risks.',
      'Debugged and traced memory allocations using GDB, monitoring registers and stack behavior.',
      'Conducted post-exploit analysis testing ASLR and stack protection countermeasures.',
    ],
    architecture: {
      nodes: [
        { id: 'vuln',   label: 'Vulnerable Binary', sublabel: 'C / 32-bit',          color: 'blue',   row: 0, col: 0 },
        { id: 'input',  label: 'Crafted Input',     sublabel: 'Payload / Shellcode',  color: 'amber',  row: 1, col: 0 },
        { id: 'stack',  label: 'Stack Overflow',    sublabel: 'Return Addr Overwrite', color: 'purple', row: 2, col: 0 },
        { id: 'heap',   label: 'Heap Overflow',     sublabel: 'Metadata Corruption', color: 'purple', row: 2, col: 1 },
        { id: 'fmt',    label: 'Format String',     sublabel: '%x · %n Exploit',     color: 'purple', row: 2, col: 2 },
        { id: 'gdb',    label: 'GDB Analysis',      sublabel: 'Register · Stack Trace', color: 'blue', row: 3, col: 0 },
        { id: 'aslr',   label: 'ASLR Bypass',       sublabel: 'Countermeasure Test', color: 'amber',  row: 4, col: 0 },
        { id: 'root',   label: 'Root Access',       sublabel: 'Privilege Escalation', color: 'green',  row: 5, col: 0 },
      ],
      edges: [
        { from: 'vuln', to: 'input' }, { from: 'input', to: 'stack' },
        { from: 'input', to: 'heap' }, { from: 'input', to: 'fmt' },
        { from: 'stack', to: 'gdb' }, { from: 'heap', to: 'gdb' },
        { from: 'fmt', to: 'gdb' }, { from: 'gdb', to: 'aslr' },
        { from: 'aslr', to: 'root' },
      ],
    },
    gallery: [
      { title: 'GDB Session', description: 'Live debugging with stack traces', type: 'terminal' },
      { title: 'Exploit Success Rates', description: 'Attack vector effectiveness', type: 'scores' },
      { title: 'Memory Map', description: 'Process memory layout', type: 'json' },
      { title: 'Lab Structure', description: 'Exploit file organization', type: 'structure' },
    ],
    insights: '### What I Explored\n\nDeep-dive into **memory exploitation** in controlled 32-bit Linux environments.\n\n### Attack Vectors Tested\n\n- **Stack smashing**: Overwriting return address to redirect execution\n- **Heap overflow**: Corrupting heap metadata for arbitrary writes\n- **Format string**: Using `%n` to write to arbitrary memory locations\n\n### Key Insight\n\n`ASLR` significantly raises the difficulty but does not prevent exploitation when combined with **information leaks** that reveal base addresses.\n\n### EC-Council Connection\n\nThis lab reinforced and extended my **Ethical Hacking Essentials** certification curriculum.',
  },
  {
    id: 'formal-language-typing-game',
    num: '04',
    name: 'Formal Language Typing Game',
    tagline: 'Theory of Computation · Tkinter · 9 Language Patterns',
    description: 'A Theory of Computation coursework project — an interactive Tkinter game that challenges players to type strings matching 9 formal language patterns in 45 seconds. Implements DFA (regex), PDA (stack-based balanced parentheses), and string reversal (palindrome) validators from scratch in pure Python.',
    stack: ['Python', 'Tkinter', 'Regex (re)', 'Stack / PDA', 'DFA', 'Automata Theory'],
    category: ['ai'],
    featured: false,
    github: 'https://github.com/darshanjoshi05',
    period: 'Oct – Dec 2024',
    overview: { type: 'Theory of Computation', status: 'Completed', year: '2024', role: 'Solo Developer' },
    stats: [
      { value: '9',   label: 'Language Patterns' },
      { value: '45s', label: 'Game Timer' },
      { value: '3',   label: 'Automata Types' },
    ],
    bullets: [
      'Built a Tkinter desktop game for Theory of Computation coursework that validates 9 formal language patterns in real-time as the player types.',
      'Implemented DFA-equivalent validators using Python regex (re module): a*b*, alternating 01, contains 101, ends in 01, a+b+c+, a*b*c*, a*b+c+.',
      'Built a stack-based PDA from scratch (no libraries) to validate balanced parentheses — pushes ( and pops on ), returns True only if stack is empty.',
      'Implemented palindrome detection using Python string reversal (sentence == sentence[::-1]) as a third automaton class.',
      'Scoring system awards +10 for correct answers, deducts -5 for wrong, with a 1-second delay before advancing on failure.',
      'Random sentence selection without repetition (tracks used_sentences), skip button, and real-time ✔️/❌ feedback labels.',
      'Pure Python with zero external dependencies — only stdlib tkinter and re modules used.',
    ],
    architecture: {
      nodes: [
        { id: 'gui',    label: 'Tkinter Window',    sublabel: 'TypingGame class',      color: 'blue',   row: 0, col: 0 },
        { id: 'input',  label: 'Entry Widget',      sublabel: 'Keyboard · Return key', color: 'blue',   row: 1, col: 0 },
        { id: 'picker', label: 'Sentence Picker',   sublabel: 'random.choice · 9 sets', color: 'purple', row: 2, col: 0 },
        { id: 'timer',  label: '45s Timer',         sublabel: 'root.after(1000)',      color: 'purple', row: 2, col: 1 },
        { id: 'dfa',    label: 'DFA / Regex',       sublabel: 're.match · 7 patterns', color: 'amber',  row: 3, col: 0 },
        { id: 'pda',    label: 'Stack PDA',         sublabel: 'Balanced parentheses',  color: 'amber',  row: 3, col: 1 },
        { id: 'pal',    label: 'Palindrome',        sublabel: 'String reversal',       color: 'amber',  row: 3, col: 2 },
        { id: 'score',  label: 'Score Engine',      sublabel: '+10 correct · -5 wrong', color: 'green', row: 4, col: 0 },
        { id: 'fb',     label: 'Feedback Label',    sublabel: '✔️ Correct / ❌ Wrong',  color: 'green',  row: 4, col: 1 },
      ],
      edges: [
        { from: 'gui', to: 'input' }, { from: 'input', to: 'picker' },
        { from: 'picker', to: 'timer' }, { from: 'picker', to: 'dfa' },
        { from: 'picker', to: 'pda' }, { from: 'picker', to: 'pal' },
        { from: 'dfa', to: 'score' }, { from: 'pda', to: 'score' },
        { from: 'pal', to: 'score' }, { from: 'score', to: 'fb' },
        { from: 'timer', to: 'score' },
      ],
    },
    gallery: [
      { title: 'Game Session', description: 'Live typing validation terminal log', type: 'terminal' },
      { title: 'Pattern Accuracy', description: 'Per-pattern validation scores', type: 'scores' },
      { title: 'Automata Config', description: '9-pattern language definitions', type: 'json' },
      { title: 'Source File', description: 'Toc_final.py single-file structure', type: 'structure' },
    ],
    insights: '### Course Context\n\nBuilt for **Theory of Computation** at Lawrence Technological University — the goal was to make abstract automata theory tangible through play.\n\n### The 9 Language Patterns\n\n- `a*b*` — zero or more as followed by zero or more bs (DFA via regex)\n- `balanced_parentheses` — stack-based PDA, stack must be empty at end\n- `palindrome` — string equals its reverse (e.g. "racecar")\n- `alternating_01` — matches `(01)*` — strictly alternating\n- `contains_101` — any string containing the substring 101\n- `ends_in_01` — any binary string ending in 01\n- `a+b+c+` — one or more of each, in order\n- `a*b*c*` — zero or more of each, in order\n- `a*b+c+` — zero as, at least one b and one c\n\n### Key Implementation Details\n\n- Stack PDA built without libraries: iterates char by char, push on `(`, pop on `)`, reject if pop on empty stack\n- `used_sentences` list prevents repetition until all 9 are exhausted, then resets\n- Timer uses `root.after(1000, self.update_clock)` — Tkinter-native, no threading\n- Wrong answers get a 1-second delay (`root.after(1000, self.next_sentence)`) to let feedback register\n\n### What I Learned\n\n- Stack machines and regex are more powerful to implement than they look on paper\n- Tkinter event loop model requires careful state management to avoid race conditions',
  },
  {
    id: 'global-harvest-imports',
    num: '05',
    name: 'Global Harvest Imports',
    tagline: 'Enterprise Relational Database · 3NF · MySQL · 7 Tables',
    description: 'End-to-end relational database design for a multi-department international agricultural import company. Deliverables include a fully normalised 3NF MySQL schema (7 tables, 5 analytical queries), seed data, ERD documentation, and a DFD-driven design process.',
    stack: ['MySQL', 'SQL', 'ERD', 'DFD', '3NF Normalization', 'Schema Design'],
    category: ['db', 'backend'],
    featured: false,
    github: 'https://github.com/darshanjoshi05',
    period: 'Jan – Jun 2024',
    overview: { type: 'Database Design', status: 'Completed', year: '2024', role: 'Database Architect' },
    stats: [
      { value: '7',   label: 'Tables' },
      { value: '3NF', label: 'Normalization' },
      { value: '5',   label: 'Departments' },
    ],
    bullets: [
      'Designed a 7-table 3NF MySQL schema: Suppliers, Categories, Products, Customers, Orders, Order_Items, Shipments — with proper FK constraints and indexes.',
      'Built Order_Items as a junction table with a GENERATED subtotal column (MySQL 5.7+) to avoid update anomalies and enforce data integrity.',
      'Applied full normalization pipeline: 1NF (atomic attributes) → 2NF (full functional dependency) → 3NF (no transitive dependencies).',
      'Wrote 5 analytical SQL queries: revenue by product, customer order history, supplier performance, monthly trend, and low-stock alerts.',
      'Executed ERD and DFD design phases to map 5-department requirements (procurement, sales, logistics, finance, operations) into a logical data model.',
      'Created seed data with realistic international suppliers (India, Brazil, Australia, Sri Lanka, Canada) and customers across 5 countries.',
    ],
    architecture: {
      nodes: [
        { id: 'req',    label: 'Requirements',    sublabel: '5 Departments',         color: 'blue',   row: 0, col: 0 },
        { id: 'dfd',    label: 'DFD',             sublabel: 'Data Flow Diagram',     color: 'blue',   row: 1, col: 0 },
        { id: 'erd',    label: 'ERD',             sublabel: '7 Entities · FK Map',   color: 'purple', row: 2, col: 0 },
        { id: 'norm',   label: 'Normalization',   sublabel: '1NF → 2NF → 3NF',      color: 'amber',  row: 3, col: 0 },
        { id: 'schema', label: 'schema.sql',      sublabel: 'Tables · Indexes',      color: 'amber',  row: 4, col: 0 },
        { id: 'seed',   label: 'seed_data.sql',   sublabel: 'Realistic Test Data',   color: 'amber',  row: 4, col: 1 },
        { id: 'query',  label: 'queries.sql',     sublabel: '5 Analytical Queries',  color: 'green',  row: 5, col: 0 },
        { id: 'db',     label: 'MySQL Database',  sublabel: 'Deployed · Indexed',    color: 'green',  row: 5, col: 1 },
      ],
      edges: [
        { from: 'req', to: 'dfd' }, { from: 'dfd', to: 'erd' },
        { from: 'erd', to: 'norm' }, { from: 'norm', to: 'schema' },
        { from: 'norm', to: 'seed' }, { from: 'schema', to: 'query' },
        { from: 'schema', to: 'db' }, { from: 'seed', to: 'db' },
        { from: 'query', to: 'db' },
      ],
    },
    gallery: [
      { title: 'SQL Schema Output', description: 'CREATE TABLE statements with constraints', type: 'terminal' },
      { title: 'Table Normalization', description: '3NF compliance per table', type: 'scores' },
      { title: 'Schema Definition', description: 'Table + FK structure JSON', type: 'json' },
      { title: 'Project Files', description: 'schema · seed · queries · erd docs', type: 'structure' },
    ],
    insights: '### Design Process\n\nFull **requirements → production-ready schema** pipeline for a multi-department international import company.\n\n### Files Delivered\n\n- `schema.sql` — 7 CREATE TABLE statements, FK constraints, performance indexes\n- `seed_data.sql` — realistic data: 5 suppliers (4 countries), 7 products, 5 customers, 5 orders\n- `queries.sql` — 5 analytical queries: revenue ranking, supplier performance, monthly trends, low-stock alerts, customer history\n- `erd_notes.md` — entity list, relationships, normalization rationale\n\n### Key Design Decisions\n\n- `subtotal` in Order_Items is a **GENERATED column** — computed automatically, no update anomaly possible\n- **ENUM for order status** (`pending → confirmed → shipped → delivered → cancelled`) enforces valid state machine\n- Separate Categories table prevents transitive dependency in Products — satisfies 3NF strictly\n- **Composite UNIQUE** on `(order_id, product_id)` prevents duplicate line items\n\n### What I Learned\n\n- Stakeholder communication is 50% of database design — requirements gathering drives everything\n- ERD-first approach prevents costly schema refactors downstream',
  },
  {
    id: 'indoor-scene-recognition',
    num: '06',
    name: 'Indoor Scene Recognition',
    tagline: 'YOLOv5 · REST API · Web App · Docker',
    description: 'A deployable indoor scene recognition system using a fine-tuned YOLOv5s model (14.4MB), served via both a REST API (restapi.py) and an interactive web application (webapp.py) built with Flask/Jinja2. Fully containerized with Docker for one-command deployment.',
    stack: ['YOLOv5', 'PyTorch', 'Python', 'Flask', 'REST API', 'Jinja2', 'Docker', 'HTML/CSS'],
    category: ['ai', 'backend'],
    featured: false,
    github: 'https://github.com/darshanjoshi05/indoor-recognition-main',
    period: '2026',
    overview: { type: 'Computer Vision', status: 'Completed', year: '2026', role: 'Solo Engineer' },
    stats: [
      { value: '14.4MB', label: 'Model Size' },
      { value: '2',      label: 'Interfaces' },
      { value: 'Docker', label: 'Deployment' },
    ],
    bullets: [
      'Fine-tuned YOLOv5s model (yolov5s.pt, 14.4MB) for indoor scene recognition with custom class detection.',
      'Built dual-interface serving layer: REST API (restapi.py) for programmatic access and interactive web app (webapp.py) for browser-based inference.',
      'Designed Jinja2-powered frontend (templates/, static/) with real-time image upload and prediction display.',
      'Containerized the full stack with Docker (Dockerfile) enabling one-command deployment anywhere.',
      'Structured test suite (tests/, test-images/) for model inference validation and API endpoint testing.',
      'Documented architecture and usage in docs/ with requirements.txt for reproducible environment setup.',
    ],
    architecture: {
      nodes: [
        { id: 'img',     label: 'Image Input',      sublabel: 'Upload · URL · Test', color: 'blue',   row: 0, col: 0 },
        { id: 'router',  label: 'Request Router',   sublabel: 'Flask · Python',      color: 'purple', row: 1, col: 0 },
        { id: 'restapi', label: 'REST API',          sublabel: 'restapi.py',          color: 'blue',   row: 2, col: 0 },
        { id: 'webapp',  label: 'Web App',           sublabel: 'webapp.py',           color: 'blue',   row: 2, col: 1 },
        { id: 'yolo',    label: 'YOLOv5s Model',    sublabel: 'yolov5s.pt · 14.4MB', color: 'purple', row: 3, col: 0 },
        { id: 'infer',   label: 'Inference Engine', sublabel: 'PyTorch · CUDA',      color: 'amber',  row: 4, col: 0 },
        { id: 'json',    label: 'JSON Response',    sublabel: 'Predictions · Scores', color: 'green',  row: 5, col: 0 },
        { id: 'ui',      label: 'Web UI',           sublabel: 'Jinja2 · Templates',  color: 'green',  row: 5, col: 1 },
      ],
      edges: [
        { from: 'img', to: 'router' },
        { from: 'router', to: 'restapi' }, { from: 'router', to: 'webapp' },
        { from: 'restapi', to: 'yolo' }, { from: 'webapp', to: 'yolo' },
        { from: 'yolo', to: 'infer' },
        { from: 'infer', to: 'json' }, { from: 'infer', to: 'ui' },
      ],
    },
    gallery: [
      { title: 'API Terminal Output', description: 'Flask server inference log', type: 'terminal' },
      { title: 'Detection Scores',    description: 'Per-class confidence scores', type: 'scores' },
      { title: 'API Response JSON',   description: 'REST endpoint output', type: 'json' },
      { title: 'Project Structure',   description: 'Dockerized repo layout', type: 'structure' },
    ],
    insights: '### What I Built\n\nA **production-deployable indoor scene recognition system** with dual serving interfaces — REST API for programmatic use and a full web app for browser-based inference.\n\n### Key Design Decisions\n\n- **YOLOv5s** chosen for the optimal accuracy/size tradeoff — 14.4MB model fits in any container\n- **Dual interface**: `restapi.py` for developers, `webapp.py` for end-users — same model, two access patterns\n- **Docker-first**: Dockerfile at root means `docker build . && docker run` is the full deployment story\n- **Jinja2 templates** give the web app a proper UI without a frontend framework\n\n### Testing\n\n- `tests/` directory with `test-images/` for inference validation\n- `requirements.txt` pins all dependencies for reproducible builds\n\n### Next Steps\n\n- GPU inference support for faster prediction\n- Multi-image batch processing endpoint\n- Deploy to cloud with auto-scaling',
  },
  {
    id: 'twitter-analytics-engagement',
    num: '07',
    name: 'Twitter Analytics & Engagement Prediction',
    tagline: 'Social Network Mining · XGBoost · Prophet · PyTorch · R²=0.852',
    description: 'A complete social network mining and engagement prediction pipeline built on a cleaned Twitter/X timeline dataset. Combines sentiment analysis, temporal behavioral analysis, and four predictive models (XGBoost, Linear Regression, Prophet time-series, PyTorch DL) achieving R²=0.852 on engagement forecasting.',
    stack: ['Python', 'Pandas', 'XGBoost', 'PyTorch', 'Prophet', 'StatsModels', 'Matplotlib', 'Seaborn', 'Plotly', 'Scikit-learn'],
    category: ['ai', 'db'],
    featured: false,
    github: 'https://github.com/darshanjoshi05',
    period: '2024 – 2025',
    overview: { type: 'Social Network Mining', status: 'Completed', year: '2025', role: 'Co-Developer' },
    stats: [
      { value: '0.852', label: 'R² Score (OLS)' },
      { value: '0.777', label: 'R² Score (XGBoost)' },
      { value: '4',     label: 'ML Models' },
    ],
    bullets: [
      'Built end-to-end Twitter analytics pipeline: data cleaning → feature engineering → predictive modeling → visualization on a real tweet dataset.',
      'Engineered temporal features including sin/hour and cos/hour cyclic encoding, likes_mean, retweet_mean per user, and day-of-week patterns.',
      'Achieved R²=0.852 with StatsModels OLS linear regression — tweet length, likes_mean, and retweet_mean as strongest predictors.',
      'Trained XGBoost Regressor (MSE=472.48, R²=0.7766) and a PyTorch deep learning model for engagement score prediction.',
      'Applied Prophet time-series forecasting to model hourly engagement fluctuations and identify optimal posting windows.',
      'Generated 10+ visualizations: tweet frequency by hour, engagement heatmap, correlation matrix, top users by activity, likes vs retweets scatter.',
      'Co-developed with Harshita Guduru as a Big Data Analytics coursework submission at Lawrence Technological University.',
    ],
    architecture: {
      nodes: [
        { id: 'data',    label: 'tweets_clean.csv', sublabel: 'Raw Twitter Dataset',   color: 'blue',   row: 0, col: 0 },
        { id: 'clean',   label: 'Data Cleaning',    sublabel: 'Pandas · NumPy',        color: 'blue',   row: 1, col: 0 },
        { id: 'feat',    label: 'Feature Eng.',     sublabel: 'sin/cos hour · agg',    color: 'purple', row: 2, col: 0 },
        { id: 'engage',  label: 'Engagement Score', sublabel: 'likes+retweets+replies', color: 'purple', row: 2, col: 1 },
        { id: 'xgb',     label: 'XGBoost',          sublabel: 'R²=0.7766',             color: 'amber',  row: 3, col: 0 },
        { id: 'ols',     label: 'OLS Regression',   sublabel: 'R²=0.852',              color: 'amber',  row: 3, col: 1 },
        { id: 'prophet', label: 'Prophet',           sublabel: 'Time-Series Forecast',  color: 'amber',  row: 3, col: 2 },
        { id: 'dl',      label: 'PyTorch DL',       sublabel: 'Deep Learning Model',   color: 'amber',  row: 3, col: 3 },
        { id: 'viz',     label: 'Visualizations',   sublabel: 'Matplotlib · Plotly',   color: 'green',  row: 4, col: 0 },
        { id: 'insight', label: 'Insights',         sublabel: 'Posting Strategy',      color: 'green',  row: 4, col: 1 },
      ],
      edges: [
        { from: 'data', to: 'clean' }, { from: 'clean', to: 'feat' },
        { from: 'feat', to: 'engage' }, { from: 'feat', to: 'xgb' },
        { from: 'engage', to: 'ols' }, { from: 'engage', to: 'prophet' },
        { from: 'engage', to: 'dl' }, { from: 'xgb', to: 'viz' },
        { from: 'ols', to: 'viz' }, { from: 'prophet', to: 'insight' },
        { from: 'dl', to: 'insight' }, { from: 'viz', to: 'insight' },
      ],
    },
    gallery: [
      { title: 'Analysis Output', description: 'Model results and key metrics', type: 'terminal' },
      { title: 'Model Scores', description: 'R² and accuracy per model', type: 'scores' },
      { title: 'Feature Config', description: 'Dataset schema and engineered features', type: 'json' },
      { title: 'Project Structure', description: 'Notebook and script layout', type: 'structure' },
    ],
    insights: '### Project Context\n\nCoursework project for **Big Data Analytics** at Lawrence Technological University (co-developed with Harshita Guduru). Goal: build a complete ML pipeline to predict tweet engagement from user behavioral data.\n\n### Dataset Features\n\n- UserID, TweetID, timestamp, Likes, RetweetCount\n- text_len, num_hashtags, num_mentions, num_urls\n- day_name, hour, engagement_score (likes + retweets + replies)\n\n### Model Results\n\n- **StatsModels OLS**: R²=0.852 — best performer. Top predictors: likes_mean, retweet_mean, text_len\n- **XGBoost**: R²=0.7766, MSE=472.48 — robust non-linear model\n- **Prophet**: Hourly engagement time-series forecasting — identifies 7AM–10AM and 7PM–9PM as peak engagement windows\n- **PyTorch**: Deep learning engagement predictor for non-linear pattern capture\n\n### Key Finding\n\n- Engagement peaks at **hour 17–19** (5–7PM) with highest average score (~22)\n- **text_len** and **num_urls** show 0.85 correlation — longer, richer tweets correlate with more engagement\n- Most high-engagement tweets come from a small set of power users (top 10 users by tweet count: 600–850 tweets each)\n\n### Visualizations Produced\n\nTweet frequency by hour, average engagement by hour, top 10 users by tweet count, correlation heatmap, total engagement by hour, likes vs retweets scatter, engagement score by tweet length',
  },
  {
    id: 'ai-srs-generator',
    num: '08',
    name: 'AI Requirements Generator',
    tagline: 'Software Engineering · FastAPI + React + Vite · SRS Automation',
    description: 'A full-stack Software Engineering coursework project that automates requirements gathering using AI. FastAPI backend exposes a /generate-requirements endpoint; React/Vite frontend lets users input a system description and instantly generates SRS-ready functional requirements.',
    stack: ['FastAPI', 'Python', 'React', 'Vite', 'Pydantic', 'CORS', 'JavaScript'],
    category: ['ai', 'backend'],
    featured: false,
    github: 'https://github.com/darshanjoshi05',
    period: '2024',
    overview: { type: 'Software Engineering', status: 'Completed', year: '2024', role: 'Solo Developer' },
    stats: [
      { value: '2',     label: 'Stack Layers' },
      { value: 'REST',  label: 'API Design' },
      { value: 'SRS',   label: 'Output Format' },
    ],
    bullets: [
      'Built FastAPI backend (main.py) with a POST /generate-requirements endpoint accepting free-text system descriptions via Pydantic BaseModel validation.',
      'Designed React/Vite frontend (App.jsx) that sends user input to the FastAPI backend and renders AI-generated SRS requirements in real-time.',
      'Configured CORS middleware to enable local cross-origin communication between Vite dev server (port 5173) and FastAPI backend.',
      'Structured response model (RequirementOutput) returning a typed List[str] of formal requirements following SRS conventions.',
      'Applied Software Engineering principles: separation of concerns, typed API contracts, stateless REST design, and iterative requirement generation.',
      'Built as coursework for Software Engineering subject — demonstrates understanding of full-stack architecture, API design, and AI-assisted SRS generation.',
    ],
    architecture: {
      nodes: [
        { id: 'ui',      label: 'React UI',          sublabel: 'App.jsx · Vite · Port 5173', color: 'blue',   row: 0, col: 0 },
        { id: 'input',   label: 'System Description', sublabel: 'User Text Input',            color: 'blue',   row: 1, col: 0 },
        { id: 'fetch',   label: 'HTTP POST',          sublabel: 'fetch() · JSON body',        color: 'purple', row: 2, col: 0 },
        { id: 'cors',    label: 'CORS Middleware',    sublabel: 'FastAPI · Port 8000',        color: 'purple', row: 3, col: 0 },
        { id: 'api',     label: '/generate-reqs',     sublabel: 'POST endpoint',              color: 'amber',  row: 4, col: 0 },
        { id: 'pydantic',label: 'Pydantic Model',     sublabel: 'RequirementInput/Output',    color: 'amber',  row: 4, col: 1 },
        { id: 'ai',      label: 'AI Generator',       sublabel: 'Requirements Engine',        color: 'purple', row: 5, col: 0 },
        { id: 'srs',     label: 'SRS Output',         sublabel: 'List[str] Requirements',     color: 'green',  row: 6, col: 0 },
      ],
      edges: [
        { from: 'ui', to: 'input' }, { from: 'input', to: 'fetch' },
        { from: 'fetch', to: 'cors' }, { from: 'cors', to: 'api' },
        { from: 'api', to: 'pydantic' }, { from: 'pydantic', to: 'ai' },
        { from: 'ai', to: 'srs' }, { from: 'srs', to: 'ui' },
      ],
    },
    gallery: [
      { title: 'API Terminal', description: 'FastAPI server and endpoint logs', type: 'terminal' },
      { title: 'Output Quality', description: 'Requirements generation metrics', type: 'scores' },
      { title: 'API Response', description: 'JSON requirements output', type: 'json' },
      { title: 'Project Files', description: 'Full-stack file structure', type: 'structure' },
    ],
    insights: '### Course Context\n\nBuilt for **Software Engineering** coursework at Lawrence Technological University. The goal was to apply SE principles — requirements engineering, API design, separation of concerns — in a working system.\n\n### Real Code Details\n\n**Backend (main.py — FastAPI)**\n- `RequirementInput`: Pydantic model with single `text: str` field\n- `RequirementOutput`: Pydantic model with `requirements: List[str]`\n- POST `/generate-requirements`: accepts system description, returns SRS requirements\n- CORS configured for `http://localhost:5173` (Vite default port)\n- GET `/` health check endpoint\n\n**Frontend (App.jsx — React + Vite)**\n- React functional component with `useState` hook\n- Sends POST request to FastAPI with user text\n- Renders generated requirements as a formatted list\n\n### SE Principles Applied\n\n- **Separation of concerns**: backend handles logic, frontend handles UI\n- **Typed contracts**: Pydantic enforces input/output schema\n- **Stateless REST**: each request is independent\n- **Iterative development**: prototype → working API → UI integration',
  },
  {
    id: 'sorting-algorithms-benchmark',
    num: '09',
    name: 'Advanced Sorting Algorithms Benchmark',
    tagline: 'TimSort · Radix Sort · Bucket Sort · Python · Performance Analysis',
    description: 'A Machine Learning / Algorithms coursework project implementing and benchmarking three advanced sorting algorithms (TimSort, Radix Sort, Bucket Sort) across three dataset types (random, nearly sorted, reversed) at sizes from 500 to 100,000 elements. Produces performance comparison visualizations.',
    stack: ['Python', 'NumPy', 'Matplotlib', 'Pandas', 'TimSort', 'Radix Sort', 'Bucket Sort'],
    category: ['ai'],
    featured: false,
    github: 'https://github.com/darshanjoshi05',
    period: '2024',
    overview: { type: 'Algorithms & ML', status: 'Completed', year: '2024', role: 'Solo Developer' },
    stats: [
      { value: '3',     label: 'Algorithms' },
      { value: '100K',  label: 'Max Dataset' },
      { value: '9',     label: 'Test Scenarios' },
    ],
    bullets: [
      'Implemented TimSort from scratch: divides array into runs sorted by insertion sort, then merges runs using merge sort — mirrors Python built-in sort.',
      'Implemented Radix Sort: processes integers least-significant to most-significant digit using counting sort as a subroutine — achieves O(nk) linear time.',
      'Implemented Bucket Sort: distributes elements into value-range buckets, sorts each bucket independently, then concatenates results.',
      'Generated 3 dataset types with NumPy: random integers, nearly-sorted (minor displacements), and reversed arrays — at sizes 500 to 100,000.',
      'Benchmarked all 9 combinations (3 algorithms × 3 dataset types) with timed execution, then visualized results with Matplotlib.',
      'Key findings: Radix Sort most consistent overall; TimSort dominates on nearly-sorted data; Bucket Sort degrades on skewed/reversed distributions.',
    ],
    architecture: {
      nodes: [
        { id: 'gen',     label: 'Dataset Generator', sublabel: 'NumPy · 500–100K',       color: 'blue',   row: 0, col: 0 },
        { id: 'rand',    label: 'Random',            sublabel: 'np.random.randint',       color: 'blue',   row: 1, col: 0 },
        { id: 'nearly',  label: 'Nearly Sorted',     sublabel: 'minor displacements',     color: 'blue',   row: 1, col: 1 },
        { id: 'rev',     label: 'Reversed',          sublabel: 'descending order',        color: 'blue',   row: 1, col: 2 },
        { id: 'tim',     label: 'TimSort',           sublabel: 'InsertSort + MergeSort',  color: 'purple', row: 2, col: 0 },
        { id: 'radix',   label: 'Radix Sort',        sublabel: 'O(nk) · LSD approach',   color: 'purple', row: 2, col: 1 },
        { id: 'bucket',  label: 'Bucket Sort',       sublabel: 'Value-range buckets',     color: 'purple', row: 2, col: 2 },
        { id: 'bench',   label: 'Benchmarker',       sublabel: 'time · 9 combinations',  color: 'amber',  row: 3, col: 0 },
        { id: 'viz',     label: 'Matplotlib Plots',  sublabel: 'Per-dataset graphs',      color: 'green',  row: 4, col: 0 },
        { id: 'result',  label: 'Results Table',     sublabel: 'Pandas DataFrame',        color: 'green',  row: 4, col: 1 },
      ],
      edges: [
        { from: 'gen', to: 'rand' }, { from: 'gen', to: 'nearly' }, { from: 'gen', to: 'rev' },
        { from: 'rand', to: 'tim' }, { from: 'rand', to: 'radix' }, { from: 'rand', to: 'bucket' },
        { from: 'nearly', to: 'tim' }, { from: 'nearly', to: 'radix' }, { from: 'rev', to: 'bucket' },
        { from: 'tim', to: 'bench' }, { from: 'radix', to: 'bench' }, { from: 'bucket', to: 'bench' },
        { from: 'bench', to: 'viz' }, { from: 'bench', to: 'result' },
      ],
    },
    gallery: [
      { title: 'Benchmark Run', description: 'Timed execution output per algorithm', type: 'terminal' },
      { title: 'Performance Scores', description: 'Relative speed per dataset type', type: 'scores' },
      { title: 'Results Config', description: 'Dataset sizes and algorithm config', type: 'json' },
      { title: 'Source Structure', description: 'Single-script implementation', type: 'structure' },
    ],
    insights: '### Course Context\n\nBuilt for **Machine Learning / Algorithms** coursework at Lawrence Technological University. Goal: empirically validate theoretical time complexity claims through real benchmarking.\n\n### Key Results\n\n- **Radix Sort**: Most consistent across all 9 scenarios — linear O(nk) complexity holds empirically\n- **TimSort**: Best on nearly-sorted data — run-detection heuristic eliminates most work when data is partially ordered\n- **Bucket Sort**: Excellent on uniform random data, degrades severely on reversed/skewed distributions (uneven bucket filling)\n\n### Implementation Details\n\n- TimSort: `RUN = 32` — standard Timsort run size. Insertion sort on runs < 32 elements, then merge. Mirrors CPython internal sort.\n- Radix Sort: LSD (Least Significant Digit) approach using counting sort as subroutine. Stable sort — preserves relative order.\n- Bucket Sort: `n_buckets = len(arr)` — each bucket covers `(max-min)/n` range. Individual bucket sort via Python `sorted()`.\n- Dataset sizes: 500, 1K, 5K, 10K, 50K, 100K — exponential scaling to reveal asymptotic behavior\n\n### What I Learned\n\n- Theoretical complexity and empirical performance diverge significantly based on data distribution\n- TimSort adaptive nature makes it practically superior to theoretically "faster" algorithms on real-world data',
  },
]

export const EDUCATION = [
  {
    degree: 'Master of Science',
    field: 'Computer Science Engineering',
    school: 'Lawrence Technological University',
    location: 'Southfield, USA',
    gpa: '3.75 / 4.0',
    period: '2024 – 2025',
    type: 'Graduate',
    gpaNote: 'US Scale',
  },
  {
    degree: 'Bachelor of Engineering',
    field: 'Computer Science Engineering',
    school: 'Sree Dattha Institute of Engineering & Science',
    location: 'Hyderabad, India',
    gpa: '6.5 / 10',
    period: '2019 – 2023',
    type: 'Undergraduate',
    gpaNote: 'Indian Scale',
  },
]

export const CERTIFICATIONS = [
  { name: 'Network Defense Essentials', issuer: 'EC-Council' },
  { name: 'Ethical Hacking Essentials', issuer: 'EC-Council' },
  { name: 'Digital Forensics Essentials', issuer: 'EC-Council' },
  { name: 'Cisco Labs Crash Course', issuer: 'EC-Council' },
  { name: 'Website Hacking Techniques', issuer: 'EC-Council' },
  { name: 'Digital Marketing', issuer: 'General' },
  { name: 'Student Ambassador Program', issuer: 'General' },
]

export const PUBLICATIONS = [
  {
    id: 'cyber-security-infrastructure',
    num: '01',
    url: 'https://www.ijaresm.com/uploaded_files/document_file/Darshan_Joshi9Suj.pdf',
    doi: '',
    citedBy: 12,
    title: 'Design and Analysis of Cyber Security Infrastructure in Large Enterprises and Organisations',
    journal: 'IJARESM',
    journalFull: 'International Journal of Advanced Research in Engineering, Science and Management',
    year: '2023',
    status: 'Published',
    domain: 'Cybersecurity',
    type: 'Research Paper',
    abstract: 'A comprehensive study on enterprise cybersecurity architectures covering risk mitigation, layered defense strategies, and scalable infrastructure design. The paper synthesizes best practices across firewalls, IDS/IPS, SIEM systems, and endpoint protection frameworks.',
    description: 'Authored a comprehensive research study on enterprise cybersecurity architectures, focusing on risk mitigation, layered defense strategies, and scalable infrastructure design. Conducted systematic literature review of security framework components to derive actionable recommendations.',
    keywords: ['Cybersecurity', 'Enterprise Architecture', 'IDS/IPS', 'SIEM', 'Firewall', 'Risk Mitigation', 'Endpoint Protection'],
    points: [
      'Authored a comprehensive research study on enterprise cybersecurity architectures, focusing on risk mitigation, layered defense strategies, and scalable infrastructure design.',
      'Conducted systematic literature review of security framework components (firewalls, IDS/IPS, SIEM, endpoint protection) to derive actionable recommendations.',
      'Synthesized complex technical findings into a formal research manuscript, demonstrating disciplined documentation and analytical reasoning.',
      'Managed end-to-end research workflow including conceptualization, data collection, critical evaluation, and formal publication.',
      'Analyzed real-world enterprise network topologies and proposed a layered defense-in-depth model for large organizations.',
    ],
    highlights: [
      { label: 'Focus Area', value: 'Enterprise Cybersecurity' },
      { label: 'Framework', value: 'Defense-in-Depth' },
      { label: 'Key Topic', value: 'IDS/IPS · SIEM · Firewall' },
    ],
  },
  {
    id: 'classroom-behavior-detection-pub',
    num: '02',
    url: '',
    doi: '',
    citedBy: 0,
    title: 'Classroom Behavior Detection Using YOLOv8 and Explainable AI',
    journal: 'IJSRST',
    journalFull: 'International Journal of Scientific Research in Science and Technology',
    year: '2025',
    status: 'Under Review',
    domain: 'Computer Vision / AI',
    type: 'Research Article',
    abstract: 'This paper presents a production-grade classroom behavior detection framework trained on the SCB-05 dataset using YOLOv8x on Google Colab Pro (A100 GPU). The system achieves 74.85% mAP@0.5 overall across 11+ behavioral classes, with a standout 93.5% detection accuracy on sleeping behavior. A tiled inference pipeline enables real-time deployment on CCTV/RTSP feeds. Grad-CAM explainability layers validate that the model attends to posture and body position rather than facial features, supporting responsible AI deployment in educational settings.',
    description: 'Research paper documenting the design, dataset curation, training methodology, and Grad-CAM explainability analysis of the YOLOv8-based classroom behavior detection system developed at Lawrence Technological University.',
    keywords: ['YOLOv8', 'Computer Vision', 'Behavior Detection', 'Grad-CAM', 'Explainable AI', 'PyTorch', 'Object Detection', 'Education AI'],
    points: [
      'Trained YOLOv8x on the SCB-05 dataset using Google Colab Pro (A100 GPU), achieving 74.85% mAP@0.5 across 11+ behavioral classes.',
      'Achieved 93.5% detection accuracy on sleeping behavior — the highest per-class precision in the model.',
      'Built tiled inference pipeline for real-time CCTV/RTSP feed processing for live classroom monitoring.',
      'Curated and annotated the SCB-05 multi-class dataset via Roboflow with rigorous quality control.',
      'Integrated Grad-CAM heatmap visualization confirming model attends to posture over facial features.',
      'Proposed RTSP-based deployment architecture for resource-constrained campus hardware.',
    ],
    highlights: [
      { label: 'Model', value: 'YOLOv8x · A100 GPU' },
      { label: 'mAP@0.5', value: '74.85% Overall' },
      { label: 'Top Class', value: '93.5% Sleeping AP' },
    ],
  },
  {
    id: 'earthquake-prediction-cnn-lstm',
    num: '03',
    url: 'https://www.sciencepublishinggroup.com/article/10.11648/j.ajce.20251305.14',
    doi: '10.11648/j.ajce.20251305.14',
    citedBy: 0,
    title: 'Earthquake Prediction and Synthetic Seismogram Generation Using Hybrid CNN-LSTM Model',
    journal: 'American Journal of Civil Engineering',
    journalFull: 'American Journal of Civil Engineering',
    year: '2025',
    status: 'Published',
    domain: 'Deep Learning / Seismology',
    type: 'Research Paper',
    abstract: 'This paper presents a hybrid CNN-LSTM deep learning architecture for earthquake prediction and the generation of synthetic seismograms. The model leverages convolutional layers for spatial feature extraction from seismic waveform data and LSTM layers for temporal sequence modeling, enabling accurate magnitude prediction and realistic synthetic seismogram synthesis for data augmentation and simulation purposes.',
    description: 'A deep learning study combining CNN spatial feature extraction and LSTM temporal modeling to predict seismic events and generate synthetic seismograms, published in the American Journal of Civil Engineering, October 2025.',
    keywords: ['CNN', 'LSTM', 'Earthquake Prediction', 'Seismogram', 'Deep Learning', 'Hybrid Model', 'Seismology', 'Time Series'],
    points: [
      'Designed a hybrid CNN-LSTM architecture that combines convolutional spatial features with LSTM temporal sequence modeling for seismic data analysis.',
      'Developed a pipeline for processing real seismic waveform datasets and training multi-target prediction models for magnitude and location estimation.',
      'Implemented synthetic seismogram generation capabilities to augment training datasets for improved model generalization.',
      'Evaluated model performance against baseline deep learning models on established seismic datasets.',
      'Demonstrated that CNN-LSTM hybrid models outperform standalone CNN or LSTM architectures on temporal seismic prediction tasks.',
      'Published findings in the American Journal of Civil Engineering, October 30, 2025.',
    ],
    highlights: [
      { label: 'Architecture', value: 'CNN + LSTM Hybrid' },
      { label: 'Application', value: 'Seismic Prediction' },
      { label: 'Published', value: 'Oct 30, 2025' },
    ],
  },
  {
    id: 'nlp-resume-intelligence',
    num: '04',
    url: '',
    doi: '',
    citedBy: 0,
    title: 'NLP-Driven Resume Tailoring: A Modular Approach to JD-Aware Career Document Generation',
    journal: 'IJCST',
    journalFull: 'International Journal of Computer Science and Technology',
    year: '2026',
    status: 'Ready for Publication',
    domain: 'NLP / Backend AI',
    type: 'Technical Paper',
    abstract: 'This paper describes the architecture, design decisions, and evaluation of a production-grade AI job application system built with FastAPI. The system features dual extraction (NLP + LLM), ATS scoring and sanitization, adaptive learning via term memory, recruiter outreach automation, and a full web dashboard. Achieves 87%+ suitability scoring accuracy and sub-2-second generation latency across PDF, DOCX, and JSON outputs.',
    description: 'A technical paper detailing the NLP pipeline, modular architecture, and performance benchmarks of the Resume Intelligence Engine — a system for automatic, JD-aware resume generation.',
    keywords: ['NLP', 'FastAPI', 'Resume Generation', 'JD Parsing', 'Document AI', 'Python', 'ReportLab'],
    points: [
      'Architected a 25+ module production system with FastAPI backend, web dashboard, SQLite database, and full test suite.',
      'Implemented dual JD extraction pipeline: regex/NLP heuristics (jd_extract.py) + LLM-powered extraction (llm_extract.py).',
      'Designed ATS scoring engine (ats_check.py, ats_sanitize.py) ensuring 91/100 ATS compatibility on generated resumes.',
      'Built adaptive learning system (learner.py, term_memory.py) that improves skill matching accuracy over repeated use.',
      'Automated recruiter outreach with personalized email generation (recruiter_msg.py) from JD context.',
      'Benchmarked 87%+ suitability scoring accuracy and sub-2-second generation latency across PDF, DOCX, and JSON.',
    ],
    highlights: [
      { label: 'ATS Score', value: '91/100 Average' },
      { label: 'Suitability', value: '87%+ Accuracy' },
      { label: 'Modules', value: '25+ Python Files' },
    ],
  },
]

// Keep single for education page backward compat
export const PUBLICATION = PUBLICATIONS[0]

export const SKILL_GROUPS = [
  {
    title: 'AI / ML',
    items: [
      { name: 'Python', level: 95 }, { name: 'YOLOv8', level: 88 },
      { name: 'PyTorch', level: 82 }, { name: 'OpenCV', level: 80 }, { name: 'Scikit-Learn', level: 75 },
    ],
  },
  {
    title: 'Backend / APIs',
    items: [
      { name: 'FastAPI', level: 90 }, { name: 'NLP / Regex', level: 85 },
      { name: 'REST APIs', level: 88 }, { name: 'ReportLab', level: 80 }, { name: 'Jinja2', level: 75 },
    ],
  },
  {
    title: 'Languages',
    items: [
      { name: 'Python', level: 95 }, { name: 'C / C++', level: 80 },
      { name: 'Java', level: 72 }, { name: 'SQL', level: 78 }, { name: 'HTML/CSS', level: 82 },
    ],
  },
  {
    title: 'Security',
    items: [
      { name: 'Buffer Overflow', level: 85 }, { name: 'GDB Debugging', level: 80 },
      { name: 'Network Defense', level: 75 }, { name: 'Digital Forensics', level: 72 }, { name: 'Ethical Hacking', level: 70 },
    ],
  },
]
